spring:
  #upload size changes
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #Data related properties
  datasource:
    url: jdbc:h2:file:./.data/quad-sol;AUTO_SERVER=TRUE
    username: admin
    password:
    driverClassName: org.h2.Driver
  #In memory DB
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update

#Security related properties
jwt:
  secret: YmFzZTY0RW5jb2RlZFNlY3JldEtleVF1YWRTb2x1dGlvbnM=
  expiration: 3600000
  refreshExpiration: 864000000

#Server related properties
server:
  servlet:
    context-path: /api