spring:
  #upload size changes
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #Data related properties
  datasource:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

#Security related properties
jwt:
  secret: YmFzZTY0RW5jb2RlZFNlY3JldEtleVF1YWRTb2x1dGlvbnM=
  expiration: 8640000000
  refreshExpiration: 864000000

#Server related properties
server:
  servlet:
    context-path: /api